spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: enriquebravo115@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:
              true: true
      #server:
      #  ssl:
      #    key-store-type: PKCS12
      #    key-store: classpath:certificate.p12
      #    key-store-password: password
jwt:
  secret: qM5z2D7NDo8hnB6TVtX6KaZ5kQO+f7hwTcdI/3yfcW4=
  expiration: 36000000
  issuer: api
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
