server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globlalcors:
        corsConfigurations:
          '[/api/v1/**]':
            allowedOrigins: "http://localhost:3000"
            exposedHeaders: "page-total-count"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT 
            - DELETE
            - PATCH
            - OPTIONS
            - HEAD
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
