server:
  port: 8081

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/transaction_db
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:9090/realms/bank/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    dev.enrique.bank: DEBUG
    feign: DEBUG

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
