spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/bank
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: 9092
    consumer:
      group-id: user
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  mail:
    host: smtp.gmail.com
    port: 587
    username: testerapipersonal@gmail.com
    password: yalu erjx xclw otqr 
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      tweet-service:
        minimum-number-of-calls: 5

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:localhost}

#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:certificate.p12
#    key-store-password: password
