server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/user_db
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:9090/realms/bank/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: user-service-group
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: testerapipersonal@gmail.com
    password: yalu erjx xclw otqr 
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:9090
  realm: bank
  client-id: kong
  client-secret: kong-client-secret

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:localhost}
