spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/bank
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: testerapipersonal@gmail.com
    password: yalu erjx xclw otqr 
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

      #server:
      #  ssl:
      #    key-store-type: PKCS12
      #    key-store: classpath:certificate.p12
      #    key-store-password: password
